backend:
  name: github
  repo: peterferreira/psico-plataforma
  branch: main
  base_url: https://www.anapaulafaulhaber.com.br # URL oficial para OAuth
  auth_endpoint: api/auth # Rota da API

media_folder: "public/images/blog"
public_folder: "/images/blog"
site_url: "https://www.anapaulafaulhaber.com.br"
display_url: "https://www.anapaulafaulhaber.com.br"
logo_url: "https://www.anapaulafaulhaber.com.br/mental_health_abstract.png"

collections:
  - name: "blog"
    label: "Artigos do Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Descrição Curta (SEO)", name: "description", widget: "text" }
      - { label: "Conteúdo do Artigo", name: "body", widget: "markdown" }
